//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_ru {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_ru() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.SharedResource_ru", typeof(SharedResource_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string name_already_taken {
            get {
                return ResourceManager.GetString("name_already_taken", resourceCulture);
            }
        }
        
        internal static string name_required {
            get {
                return ResourceManager.GetString("name_required", resourceCulture);
            }
        }
        
        internal static string team_already_exists {
            get {
                return ResourceManager.GetString("team_already_exists", resourceCulture);
            }
        }
        
        internal static string team_not_found {
            get {
                return ResourceManager.GetString("team_not_found", resourceCulture);
            }
        }
        
        internal static string user_already_has_team {
            get {
                return ResourceManager.GetString("user_already_has_team", resourceCulture);
            }
        }
        
        internal static string user_is_not_scrum_master {
            get {
                return ResourceManager.GetString("user_is_not_scrum_master", resourceCulture);
            }
        }
        
        internal static string user_not_found {
            get {
                return ResourceManager.GetString("user_not_found", resourceCulture);
            }
        }
    }
}
